language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
before_install:
  - [[ "$TRAVIS_NODE_VERSION" ~= "0.8" ]] && node -e "var p = require('package'); delete p.dependencies['grunt-contrib-jshint']; require('fs').writeFileSync('package.json', JSON.stringify(p));"
